version: '3.8'

services:
  ingestion:
    build: .
    command: python mock_telemetry.py
    environment:
      - PYTHONUNBUFFERED=1

  models:
    build: .
    command: python ml_engine.py
    environment:
      - PYTHONUNBUFFERED=1

  orchestrator:
    build: .
    command: python ml_orchestrator.py
    environment:
      - PYTHONUNBUFFERED=1

  ui:
    build: .
    ports:
      - "8501:8501"
    command: streamlit run dashboard.py
    environment:
      - PYTHONUNBUFFERED=1